plugins {
    id 'java'
    id 'idea'
    id 'com.google.protobuf' version '0.10.0'
}

group = 'elc1018.grpc.chat'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def grpcVersion = '1.80.0' // CURRENT_GRPC_VERSION
def protobufVersion = '3.25.8'
def protocVersion = protobufVersion

dependencies {
    implementation "io.grpc:grpc-netty-shaded:${grpcVersion}"
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "io.grpc:grpc-services:${grpcVersion}"
    implementation "io.grpc:grpc-stub:${grpcVersion}"

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

protobuf {
    protoc { artifact = "com.google.protobuf:protoc:${protocVersion}" }
    plugins {
        grpc { artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}" }
    }
    generateProtoTasks {
        all()*.plugins { grpc {} }
    }
}

test {
    useJUnitPlatform()
}

tasks.register('runServer', JavaExec) {
    group = 'application'
    description = 'Executa o servidor'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'elc1018.grpc.chat.server.ChatServer'

    if (project.hasProperty('port')) {
        args(project.property('port').toString())
    }

    standardInput = System.in
}

tasks.register('runClient', JavaExec) {
    group = 'application'
    description = 'Executa o cliente'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'elc1018.grpc.chat.client.ChatClient'

    def command = (project.findProperty('command') ?: 'register').toString()
    def host = (project.findProperty('host') ?: 'localhost:50051').toString()
    def username = (project.findProperty('username') ?: 'user').toString()

    args(command, host, username)

    standardInput = System.in
}
